apiVersion: v1
kind: Service
metadata:
  name: core-svc
  labels:
    app: core
spec:
  selector:
    app: core
  ports:
  - name: tcp-client
    port: 4222
    protocol: TCP
  - name: tcp-cluster
    port: 7673
    protocol: TCP