apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-cm
  label:
    app: nats
data:
  nats.conf: |
    server_name: $SERVER_NAME
    listen: 4222
    http: 8222
    
    jetstream {
      store_dir=/nats/storage
    }
    
    cluster {
      name: nats-cluster
      listen: 6222
      routes: [
        nats-route://nats-0.nats-hlsvc.default.svc.cluster.local:6222
        nats-route://nats-1.nats-hlsvc.default.svc.cluster.local:6222
        nats-route://nats-2.nats-hlsvc.default.svc.cluster.local:6222
      ]
      connect_retries: 30
    }